language: python
python:
  - '3.8'

services:
  - postgresql

addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13

env:
  global:
  - PGPORT=5433

before_install:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  - sudo service postgresql@13-main restart
  
before_script:
  - pip install -r requirements.txt
  - psql -p 5433 -U postgres -c 'create database travis_ci_test;'

branches: 
  only:
    - staging

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

script:
  - python manage.py test