language: python
python:
  - '3.8'

services:
  - postgresql

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
  global:
  - PGPORT=5433
  - PGUSER=travis

before_script:
  - pip install -r requirements.txt
  - dpkg -l | grep postgresql
  - psql -c 'create database travis_ci_test;' -U postgres

branches: 
  only:
    - staging

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

script:
  - python manage.py test
