language: python
python:
  - '3.8'

addons:
  postgresql: "9.4"
  
before_script:
  - pip install -r requirements.txt

branches: 
  only:
    - staging

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

services:
  - postgresql

script:
  - python manage.py test
