language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt
  - dpkg -l | grep postgresql
  - psql -c 'create database travis_ci_test;' -U postgres

branches: 
  only:
    - staging

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

services:
  - postgresql

script:
  - python manage.py test
