# Generated by Django 4.0.4 on 2022-09-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_substitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='store',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
