# Generated by Django 4.0.4 on 2022-09-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_substitution', '0002_alter_products_categories_alter_products_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='products',
            name='store',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
